name: Test build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install snapcraft
        run: |
          sudo snap install snapcraft --classic


      - name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft
        with:
          snapcraft-args: "--destructive-mode"

      - name: Upload snap
        uses: actions/upload-artifact@v6
        with:
          name: xenia-canary-x64-snap
          path: ${{ steps.snapcraft.outputs.snap }}

      - name: Publish snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: canary
