name: Test build
on:
  push:
    branches: [ appimage ]
  pull_request:
    branches: [ appimage ]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install snapcraft and update deps
        run: |
          sudo snap install snapcraft --classic
          sudo apt-get update

      - name: Build snap
        run: |
          sudo snapcraft pack --destructive-mode

      - name: Upload snap
        uses: actions/upload-artifact@v6
        with:
          name: xenia-canary-x64-snap
          path: "*.snap"

      - name: Publish snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: "*.snap"
          release: canary
