name: Test build
on:
  push:
    branches: [ appimage ]
  pull_request:
    branches: [ appimage ]
  workflow_dispatch:
  workflow_call:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install snapcraft and update deps
        run: |
          sudo snap install snapcraft --classic
          sudo apt-get update

      - name: Build snap
        run: |
          sudo snapcraft pack --destructive-mode
          # man I wish snapcore/action-publish
          # supported globstars
          # but because it does not we have to pass path as an ENV
          # version num will be variable so this is required
          snap=$(ls *.snap | head -n 1)
          echo "SNAP_PATH=$snap" >> $GITHUB_ENV

      - name: Upload snap
        uses: actions/upload-artifact@v6
        with:
          name: xenia-canary-x64-snap
          path: "*.snap"

      - name: Publish snap
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        run: |
          snapcraft upload $SNAP_PATH --release candidate

  create-github-release:
    name: Release to GitHub
    needs: [test-build]
    uses: ./.github/workflows/release.yml
