name: Test build (debug)
on:
  pull_request:
    branches: [ appimage ]
  workflow_dispatch:
  workflow_call:

jobs:
  test-build-no-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: appimage

      - name: Install snapcraft and update deps
        run: |
          sudo snap install snapcraft --classic
          sudo apt-get update

      - name: Build snap
        run: |
          sudo snapcraft pack --destructive-mode

      - name: Upload snap
        uses: actions/upload-artifact@v6
        with:
          name: xenia-canary-x64-snap
          path: "*.snap"

      - name: Publish snap
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        run: |
          # binary names vary
          # cuz of to rapidly changing version number
          # so this ls is needed
          snapcraft upload $(ls *.snap | head -n 1) --release candidate
