name: Updates from upstream

on:
  schedule:
    - cron: '0 0 * * 1,4,0'
  workflow_dispatch:

jobs:
  update-snap:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git

      - name: Install snapcraft daemon
        uses: samuelmeuli/action-snapcraft@v3

      - name: Get latest tag
        id: get_tag
        run: |
          # get latest release
          RELEASE=$(curl -s https://api.github.com/repos/xenia-canary/xenia-canary/releases/latest | jq -r .tag_name)
          echo "tag=$RELEASE" >> $GITHUB_OUTPUT

      - name: Update version in snapcraft.yaml
        run: |
          # update version line
          sed -i "s/^version: .*/version: '${{ steps.get_tag.outputs.tag }}'/" snapcraft.yaml

      - name: Commit and push
        run: |
          # set author to actions
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add snapcraft.yaml # add the one file we change
          # check for any commits
          if git diff --quiet && git diff --staged --quiet; then
            echo "Ehh, nothin's new. Peace out."
            exit 1
          fi
          # else do the commit
          git commit -m "Bump version to ${{ steps.get_tag.outputs.tag }}"
          git push

      - name: Verify commit
        run: |
          local=$(git rev-parse HEAD)
          branch=$(git rev-parse --abbrev-ref HEAD)
          
          echo "Verifying $local"
          
          for i in {1..10}; do
            git fetch origin "$branch" --quiet
            
            # check if local sha is in remote backlogs
            if git merge-base --is-ancestor "$local" "origin/$branch"; then
              echo "$local is on remote, so building in 5s"
              sleep 5
              exit 0
            fi
          
            echo "Commit isn't on remote... trying again"
            sleep 10
          done
          
          echo "Error: Took too long and remote lacks local commit anywhere. Check for any problems and try again."
          exit 1
  build-after-publish:
    name: Build snap
    needs: [update-snap]
    uses: ./.github/workflows/build.yml
    secrets: inherit
